---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
  namespace: awx
spec:
  ingress_type: ingress
  hostname: myawxserver
  postgres_storage_class: rook-ceph-block
  postgres_data_volume_init: true
  postgres_init_container_commands: |
    chown -R 26:0 /var/lib/pgsql/data
    chmod 700 /var/lib/pgsql/data
